apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-nginx.yaml
images:
  - name: nginx
    newName: nginx
    newTag: 1.16.0
commonAnnotations:
  kubernetes.io/change-cause: "Initial deployment with 1.16.0"
